export const newsArticles = [
  {
    index: '01',
    title: 'Istanbul Blockchain Week',
    description: 'Bridgr hosted the official Istanbul Blockchain Week afterparty.',
    date: 'Nov 14th 2022',
    link: 'https://twitter.com/Bridgrxyz/status/1592214170996703232?s=20',
    imgUrl: '/istanbulnews.jpg',
    altText: 'Istanbul Event',
  },
  {
    index: '02',
    title: 'Singapore Social',
    description: "Singapore's first NFT bar hosted a sold out Bridgr Web3 Social.",
    date: 'Feb 3rd 2023',
    link: 'https://twitter.com/Bridgrxyz/status/1622586625552429057?s=20',
    imgUrl: '/singaporefeb.jpg',
    altText: 'Singapore Event',
  },
  {
    index: '03',
    title: 'Beachside in Bali',
    description: 'We hit the tropics and threw a red carpet event in Bali.',
    date: 'Feb 24th 2023',
    link: 'https://twitter.com/Bridgrxyz/status/1625104846675386369?s=20',
    imgUrl: '/balinews.jpg',
    altText: 'Bali Event',
  },
  {
    index: '04',
    title: 'Istanbul Keynote Panel',
    description: "How Web3 can help in emergencies like Turkey's earthquakes.",
    date: 'April 1st 2023',
    link: 'https://twitter.com/Bridgrxyz/status/1644964278833905667?s=20',
    imgUrl: '/istanbul_dj.jpg',
    altText: 'Istanbul Event',
  },
  {
    index: '05',
    title: 'NFT NYC',
    description: 'NFT.NYC after party with the worlds first CryptoPunk band and live DJ.',
    date: 'April 12th 2023',
    link: 'https://twitter.com/Bridgrxyz/status/1650437870321291269?s=20',
    imgUrl: '/gamehaus_game.jpg',
    altText: 'NFT NYC Event',
  },
  {
    index: '06',
    title: 'Bitcoin Miami',
    description: 'Beachside social with some of the brightest minds in Web3.',
    date: 'May 18th 2023',
    link: 'https://www.eventbrite.sg/e/bitcoin-2023-miami-beach-side-networking-on-may-18th-eden-roc-hotel-tickets-632009837437',
    imgUrl: '/edenroc.webp',
    altText: 'Miami Event',
  },
  {
    index: '07',
    title: 'Web3 Social India',
    description: "Bridgr is hosting CryptoFemale India's first Web3 social in India's 'Silicon Valley', Bangalore.",
    date: 'June 16th 2023',
    link: 'https://medium.com/@bridgrxyz/cryptofemale-india-celebrate-their-first-offline-event-on-june-16th-in-bangalore-supported-by-cdd5d6ecf571',
    imgUrl: '/draperhouse.jpeg',
    altText: 'India Event',
  },
]

export const learnArticles = [
  {
    index: '01',
    author: 'Ethlas',
    logo: '/ethlas_white.png',
    date: '18th May 2023',
    type: 'Education',
    link: 'hackers-learn',
    imgUrl: '/fraud_news.jpg',
    title: 'How Hackers Get Private Keys',
    description: `Theft of private keys, obtaining users' authorisation or compromise of 3rd party smart contracts.`,
  },
  {
    index: '02',
    author: 'Bridgr',
    logo: '/b-logo-text-white.svg',
    date: '18th May 2023',
    type: 'Education',
    imgUrl: '/grain_bg.jpg',
    title: 'How To Build A Web3 Business',
    description: `A step-by-step guide on how to build a Web3 business`,
  },
  {
    index: '03',
    author: 'Bighaus',
    logo: '/bighaus.png',
    date: '18th May 2023',
    type: 'News',
    imgUrl: '/fraud_news.jpg',
    title: 'Monetising Your NFTs',
    description: `Turning jpegs into money and having fun while doing it`,
  },
  {
    index: '04',
    author: 'Bridgr',
    logo: '/globalb.png',
    date: '18th May 2023',
    type: 'Education',
    imgUrl: '/mark_talk.jpg',
    title: 'Building Partnerships In Web3',
    description: `Theft of private keys, obtaining users' authorisation or compromise of 3rd party smart contracts`,
  },
  {
    index: '05',
    author: 'Bridgr',
    logo: '/b-logo-text-white.svg',
    date: '20th May 2023',
    type: 'Education',
    imgUrl: '/grain_bg.jpg',
    title: 'The Ideal Web3 Business Model',
    description: `Theft of private keys, obtaining users' authorisation or compromise of 3rd party smart contracts`,
  },
  {
    index: '06',
    author: 'Bridgr',
    logo: '/b-logo-text-white.svg',
    date: '25th May 2023',
    type: 'Research',
    imgUrl: '/jacob_talk.jpg',
    title: 'The Future of Web3',
    description: `Theft of private keys, obtaining users' authorisation or compromise of 3rd party smart contracts`,
  },
];

export const partnerLogos = [
  {
    index: '01',
    link: '',
    message: '',
    imgUrl: '',
    altText: '',
    maxWidth: '',
  },
  {
    index: '02',
    link: '',
    message: '',
    imgUrl: '',
    altText: '',
    maxWidth: '',
  },
  {
    index: '03',
    link: '',
    message: '',
    imgUrl: '',
    altText: '',
    maxWidth: '',
  },
  {
    index: '04',
    link: '',
    message: '',
    imgUrl: '',
    altText: '',
    maxWidth: '',
  },
  {
    index: '05',
    link: '',
    message: '',
    imgUrl: '',
    altText: '',
    maxWidth: '',
  },
  {
    index: '06',
    link: '',
    message: '',
    imgUrl: '',
    altText: '',
    maxWidth: '',
  },
  {
    index: '07',
    link: '',
    message: '',
    imgUrl: '',
    altText: '',
    maxWidth: '',
  },
  {
    index: '08',
    link: '',
    message: '',
    imgUrl: '',
    altText: '',
    maxWidth: '',
  },
  {
    index: '09',
    link: '',
    message: '',
    imgUrl: '',
    altText: '',
    maxWidth: '',
  },
]

export const friendLogos = [
  {
    index: '01',
    link: 'https://www.quillaudits.com/smart-contract-audit',
    message: 'Smart Contracts Auditing Services, DeFi Safety Audits.',
    imgUrl: '/QA_Extended_White.png',
    altText: 'Quill Audits',
    maxWidth: 'max-w-[100%]',
  },
  {
    index: '02',
    link: 'https://nordek.io/',
    message: 'Lightspeed Blockchain Ecosystem for Payments and Gaming.',
    imgUrl: '/nordek.png',
    altText: 'Nordek',
    maxWidth: 'sm:max-w-[95%] max-w-[100%]',
  },
  {
    index: '03',
    link: 'https://www.edns.domains/',
    message: 'Decentralized name service providing domain names for Web3, including NFT, crypto wallets, web hosting, DeFi ID, and GameFi ID.',
    imgUrl: '/edns.png',
    altText: 'EDNS',
    maxWidth: 'sm:max-w-[90%] max-w-[100%]',
  },
  {
    index: '04',
    link: 'https://twitter.com/youplaceapp',
    message: 'Istanbul based Web3 event space, coworking space, community hub, cafe and bar.',
    imgUrl: '/youplacewhite.png',
    altText: 'You Place',
    maxWidth: 'sm:max-w-[65%] max-w-[80%]',
  },
  {
    index: '05',
    link: 'https://wearelight.house/',
    message: 'Bali based multi-level podcast & video production complex, creative space, entrepreneur community, cafe, bar and events space.',
    imgUrl: '/lighthouse_com.png',
    altText: 'Lighthouse Studios Bali',
    maxWidth: 'sm:max-w-[75%] max-w-[90%]',
  }
]